### ISSUE TITLE
Fix tests failing on AppVeyor

### ISSUE THREAD

**Issue by mikeharder** [aspnet/ServerTests#112]
14 tests started failing on AppVeyor after an update to dependencies.props (https://github.com/aspnet/ServerTests/commit/46e3c69458216547446347bd6f3371a26fe779e2).  Here's the error message from IIS:

```
Most likely causes:
* A module is referenced in configuration, but the module has not been installed or the name of the module is misspelled.
* IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error
  depends on which module handles the request and what was happening in the worker process when this error occurred.
* IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.
* IIS was not able to process configuration for the Web site or application.
* The authenticated user does not have permission to use this DLL.
```

AppVeyor history: https://ci.appveyor.com/project/aspnetci/servertests/history

**Comment by jkotalik** [comment]
The issue is we need to update the schema to include the inprocess hosting element on appveyor. See: https://github.com/aspnet/IISIntegration/blob/dev/tools/update_schema.ps1. Should be a quick fix.
