### ISSUE TITLE
How to listener multiple web site on WebListener 

### ISSUE THREAD

**Issue by lmxin123** [aspnet/ServerTests#19]
How to listening multiple web site on "web": "Microsoft.AspNet.Server.WebListener --server.urls.
For example, I have http://site1.com,http://site2.com,http://site3.com
How can I hosting multiple web site on one server without iis?

**Comment by Tratcher** [comment]
It's a semicolon separated list:
`"web": "Microsoft.AspNet.Server.WebListener --server.urls http://site1.com;http://site2.com;http://site3.com"`

**Comment by lmxin123** [comment]
@Tratcher  I mean, a project is an independent site, I should be how to deploy on one server without iis?

**Comment by Tratcher** [comment]
You mean you have three sites in three separate projects and you want them to all share the same port (80)? With WebListener that should just work if you start them up in their own processes:
`"web": "Microsoft.AspNet.Server.WebListener --server.urls http://site1.com"`
`"web": "Microsoft.AspNet.Server.WebListener --server.urls http://site2.com"`
`"web": "Microsoft.AspNet.Server.WebListener --server.urls http://site3.com"`

With the usual caveats that you need to either run as admin or pre-register the addresses with netsh.

If you want to run them all in the same process that should be doable in RC2 by following a sample like this and creating three `IWebHost` instances: https://github.com/aspnet/Hosting/blob/dev/samples/SampleStartups/StartupExternallyControlled.cs

**Comment by lmxin123** [comment]
Yes,I want  them to all share the same port (80). But I want to run them in the difference process on one server.Just like in the IIS to build different sites, it has a different application pool。
