### ISSUE TITLE
ServerTests only target net451

### ISSUE THREAD

**Issue by pranavkm** [aspnet/ServerTests#34]
Consequently we run none of these tests in cross plat

cc @BrennanConroy

**Comment by BrennanConroy** [comment]
Need to check other repos for similar issues

**Comment by Tratcher** [comment]
oh... The tests are like this because some of the infrastructure requires net451 (like IIS). Core CLR tests are still run on Windows because the target framework is selected inside the test and it launches a sub process.

Needs work for x-plat.

**Comment by BrennanConroy** [comment]
Fixed in https://github.com/aspnet/ServerTests/commit/b8422416f58895289645384bf9350ed68c5379cd
