### ISSUE TITLE
Add test scenarios for running on full IIS

### ISSUE THREAD

**Issue by pranavkm** [aspnet/ServerTests#47]
We're missing coverage for tests running on full IIS. The plan is to add additional tests that are conditionally enabled and use the latest build of ANCM (https://github.com/aspnet/ServerTests/issues/46) to run some E2E scenarios.

**Comment by Tratcher** [comment]
Note we already have the tests (https://github.com/aspnet/ServerTests/blob/dev/test/ServerComparison.FunctionalTests/HelloWorldTest.cs#L52) and some of the infrastructure, it has just been disabled due to the admin and install requirements.

**Comment by jkotalik** [comment]
We have full E2E tests for IIS now in IISIntegration; we probably don't need tests here as ServerTests doesn't give us any added coverage.
