### ISSUE TITLE
ResponseTests are flaky on CI

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/ServerTests#63]
ResponseTests have been failing on Win10 with this error.

```
System.OperationCanceledException : Failed to connect, retry canceled.
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.<RetryRequest>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServerComparison.FunctionalTests.ResponseTests.<ResponseFormats>d__15.MoveNext() in C:\BuildAgent\work\2b0c8ce712895332\.r\ServerTests\test\ServerComparison.FunctionalTests\ResponseTests.cs:line 187
```

There were other errors in the log too, such as 
```
Microsoft.AspNetCore.Server.HttpSys.HttpSysException (0x80004005): The process cannot access the file because it is being used by another process
```
but it's hard to tell if the errors are associated with this particular test failure.

http://aspnetci/viewLog.html?buildId=193325&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe

**Comment by muratg** [comment]
Assigning to @anurse for investigation.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/ServerTests/pull/64 should help

**Comment by anurse** [comment]
There are also some background-thread termination issues that @mikeharder found. See http://aspnetci/viewLog.html?buildId=193847&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest for example

**Comment by natemcmaster** [comment]
Could this be related to the reason Win8 builds continually fail to start?

![image](https://cloud.githubusercontent.com/assets/2696087/24466110/82057ef2-1464-11e7-884e-fd4fd4a3c24a.png)

**Comment by anurse** [comment]
Possibly, if something is staying open. We've see occasions where the processes we spawn fail to shut down.

**Comment by natemcmaster** [comment]
I'm going to open a separate issue for this ☝️

**Comment by anurse** [comment]
We've done deflaking and aren't seeing this as often. FYI @ryanbrandenburg , in case it comes up again.
