### ISSUE TITLE
IIS Express tests: orphaned iis process fails to shutdown

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/ServerTests#66]
The last 10 builds of ServerTests on Win8 have failed because the previous test run failed to shutdown. The iisexpress.exe process does not die and locks the folder. The process can only be killed with admin rights.  This leads to the following error:

![image](https://cloud.githubusercontent.com/assets/2696087/24515036/27c14ee0-152b-11e7-8181-a28f49c9bb7a.png)

![image](https://cloud.githubusercontent.com/assets/2696087/24515047/2f752ed6-152b-11e7-8587-dadf54694385.png)

![image](https://cloud.githubusercontent.com/assets/2696087/24515298/11721f10-152c-11e7-9f41-b6fecc1e4901.png)

http://aspnetci/viewType.html?buildTypeId=XPlat_Windows_Win8_Universe

**Comment by natemcmaster** [comment]
Test that is most suspect: 

ServerComparison.FunctionalTests.ResponseCompressionTests.ResponseCompression_Windows_NoCompression(serverType: IISExpress, runtimeFlavor: Clr, architecture: x64, applicationBaseUrl)

This ran for 2 hours before TC killed it. All subsequent builds failed.

**Comment by anurse** [comment]
> The process can only be killed with admin rights

This seems very concerning... our tests don't run as Admin do they?

**Comment by natemcmaster** [comment]
Yes, concerning. The build runs under our normal build agent user, but I was unable to kill iisexpress.exe without elevating Process Explorer to run as admin.

**Comment by anurse** [comment]
I'm seeing this on another box (aspnetci-a-100), with a different test. So it seems unrelated to the test, but it is a relatively consistent problem. What I don't get is how `iisexpress` is somehow elevating.

**Comment by natemcmaster** [comment]
Same issue occurs in IIS Integration.

```
stderr: warning: failed to remove .r/IISIntegration/test/FunctionalTests/bin/Release/net46
```

**Comment by muratg** [comment]
@anurse do you have time to investigate this one as well?

**Comment by anurse** [comment]
At this point we're not going to get any more information unless we start running `procmon` while running the tests. Nobody knows why the process ended up with an Admin token.

**Comment by natemcmaster** [comment]
We've added a call to `taskkill /f /im iisexpress.exe` in CI settings at the end of our test runs to mitigate this.

**Comment by anurse** [comment]
Should we close this for now? We can always reopen if it reoccurs.

**Comment by natemcmaster** [comment]
Depends. Do we still need to add something to integration testing to ensure iisexpress.exe is killed?

**Comment by anurse** [comment]
We already have as much code as I can find to do that. The thing we may still want to investigate is why the tests was hanging. `iisexpress` was left running because a test was hanging and TeamCity killed it, which orphaned `iisexpress`

**Comment by natemcmaster** [comment]
Let's close as done for now. If iisexpress is left running because a test hangs, TC will fail the build with a timeout failure. The main work we needed here was to prevent those kinds of failures from breaking the agent on future builds.
