### ISSUE TITLE
Unskip the standalone tests which were disabled temporarily

### ISSUE THREAD

**Issue by kichalla** [aspnet/ServerTests#73]

**Comment by kichalla** [comment]
Commit: 1d3747c071071dc269c0e0e987126cdefcea87a7

**Comment by Tratcher** [comment]
Why were they disabled?

**Comment by kichalla** [comment]
There are some issues running them along with new CLI and shared runtime. The standalone tests were disabled on MusicStore too. I plan to merge https://github.com/aspnet/Hosting/pull/1010 first and from there on work on these issues

**Comment by kichalla** [comment]
b52430674f1c99b8985b3e3da155a27dc959bfa7
