### ISSUE TITLE
Reenable IISExpress NTLM tests

### ISSUE THREAD

**Issue by HaoK** [aspnet/ServerTests#8]
Need to investigate root cause

**Comment by HaoK** [comment]
Failed due to AuthN behavior changes most likely

**Comment by Tratcher** [comment]
This is the same test you had to update in the Helios repo. Helios doesn't implement IAuthFeature yet so Challenge has no effect. You have to set 401 instead. I'll fix it when I implement the interface for Helios.

**Comment by Tratcher** [comment]
Done
