### ISSUE TITLE
ResponseCompressionTests.ResponseCompression_Windows_AppCompression fails on Win7 and WS08R2

### ISSUE THREAD

**Issue by mikeharder** [aspnet/ServerTests#81]
```
[ServerComparison.FunctionalTests.ResponseCompressionTests.ServerComparison.FunctionalTests.ResponseCompressionTests.ResponseCompression_Windows_AppCompression(serverType: IISExpress, runtimeFlavor: CoreClr, architecture: x64, applicationType: Standalone)]
System.NullReferenceException : Object reference not set to an instance of an object. at Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer.Dispose()
   at ServerComparison.FunctionalTests.ResponseCompressionTests.<ResponseCompression>d__12.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\ServerTests\test\ServerComparison.FunctionalTests\ResponseCompressionTests.cs:line 169
```

* http://aspnetci/viewLog.html?buildId=213999&buildTypeId=XPlat_Windows_Win7_Universe&tab=buildLog&filter=err
* http://aspnetci/viewLog.html?buildId=214101&buildTypeId=XPlat_Windows_Win2008r2_Universe&tab=buildLog&filter=err

**Comment by Tratcher** [comment]
The NullReferenceException was address via https://github.com/aspnet/Hosting/pull/1062. However, this was only a secondary exception. Now we get to see the primary error.

**Comment by mikeharder** [comment]
Root cause:

```
System.DllNotFoundException : Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.GetArchitecture()
```

Investigating if it's an issue with the `RuntimeInformation` package itself, or if ASP.NET is using the wrong version of the package.

**Comment by Eilon** [comment]
The root cause stack trace looks to be this: https://github.com/dotnet/corefx/issues/19313

But that issue isn't getting fixed, per se, as far as I can tell.

I think the conclusion in an email thread was that we might need to use higher versions of the CoreFX packages, so that this issue is avoided, but that wasn't super clear to me.

**Comment by Tratcher** [comment]
@mikeharder wasn't this only an issue for net46 which has now been removed?

**Comment by mikeharder** [comment]
Yes this appears to be a test infrastructure issue which only impacts net46.

**Comment by Eilon** [comment]
Ah, ok. So I guess we should close this then?

**Comment by mikeharder** [comment]
After I verify tomorrow the tests are passing on Win7.

**Comment by mikeharder** [comment]
Test is now passing.
