### ISSUE TITLE
Redo NTLM negative tests for netcore

### ISSUE THREAD

**Issue by Tratcher** [aspnet/ServerTests#82]
HttpClient on .NET Core does not honor UseDefaultCredentials = false for localhost (https://github.com/dotnet/corefx/issues/5045). The NTLM tests in ServerTests, IISIntegration, and HttpSysServer all start with some negative tests that expect 401s, except that HttpClient automatically handles the 401 and sends a request with credentials.

Proposal: Extract a common raw sockets HttpClient (e.g. the HttpClientSlim from Kestrel, or HttpSysServer has a similar test client). Use this for the negative tests that are currently disabled. We'll still use the normal HttpClient for the tests that need to authenticate.

**Comment by pranavkm** [comment]
Could you add this to preview2 milestone? Just so that we track this for the next release?

**Comment by Tratcher** [comment]
@muratg / @Eilon ?

**Comment by Tratcher** [comment]
No longer required for preview2. With the reintroduction of net461 test coverage this item is no longer urgent.

**Comment by Tratcher** [comment]
Note with netcoreapp2.1 preview2 the new managed HttpClientHandler (SocketsHttpHandler) no longer has this issue. We can shift the tests to use the netcoreapp2.1 TFM.

**Comment by Tratcher** [comment]
Bumping from backlog for re-triage.

**Comment by Tratcher** [comment]
Note this issue affects HttpSys, IISIntegration, ServerTests, and MusicStore.

**Comment by muratg** [comment]
@Tratcher Putting this in MQ due to higher priority work assigned to you.

**Comment by Tratcher** [comment]
Resolved by:
https://github.com/aspnet/ServerTests/commit/53564567662a09adb3c8d4c5ecbd5b4cfada1351#diff-b700d438d2dd5391288176c9b971b1d8
https://github.com/aspnet/HttpSysServer/pull/454
https://github.com/aspnet/IISIntegration/pull/833/files#diff-3bdd6282364c006363e0d50063ef68f5
https://github.com/aspnet/MusicStore/commit/0c5be39112ad853bf75ce039a60369904bbc03fd#diff-1cafe329b68cd6a05a73de5e31d1f29a
