### ISSUE TITLE
[Discussion]: New default 30 MB (~28.6 MiB) max request body size limit 

### ISSUE THREAD

**Issue by halter73** [aspnet/ServerTests#92]
This is the discussion thread for aspnet/Announcements#267.

**Comment by kspearrin** [comment]
With v1.1.2 we are currently overriding this with web.config.

```
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="105906176"/>
      </requestFiltering>
    </security>
```

Will this still work if we don't have the new `RequestSizeLimit` attribute added?

**Comment by halter73** [comment]
@kspearrin This should still work. Here's a quote form the announcement that's a little tucked away in the third paragraph:

> This limit [...] is disabled for Kestrel running behind IIS where the normal web.config limit still applies.

**Comment by kspearrin** [comment]
@halter73 Great!

**Comment by fergalmoran** [comment]
It's great to see some hard guidance around this but it would be even greater to see some official documentation for best practices around handling large file uploads in asp.net core. There are bits and pieces but most of them are either over-complicated or plain broken.

**Comment by PureKrome** [comment]
Agreed @fergalmoran  :)

Also @halter73 - where is this data being streamed to while the request is streaming in? Temp storage on disk (vs RAM)? Just thinking out loud about possible con's if someone has a really LARGE limit and get's DDOS's with large payloads to abuse this.

**Comment by Tratcher** [comment]
@PureKrome that depends on the consumer. Kestrel buffers some (much smaller) amount of data in memory per request. When those are full it puts back pressure on the socket. The form reader will spool to disk if things go over 64kb. JSON and XML get parsed in memory.

30MB matches the current IIS default.

**Comment by a-patel** [comment]
@alll
Any update?

**Comment by GordoMalvado** [comment]
Whenever i set a limit and try sending something bigger than 1100 KB, aspnet will ignore my original response and message and replace everything with a 502.3. Anyone having this issue? I have tried a ton of stuff but still not working . I just want to be able to catch (which I am able) and to give whatever response message i want!!!!

**Comment by aseemgautam** [comment]
@AndreyPereira nginx has a default limit of 1mb. I was able to solve this by adding
`client_max_body_size 20M;`

to `nginx.conf`

https://www.faqforge.com/linux/nginx-server-error-413-request-entity-too-large/

**Comment by natemcmaster** [comment]
Closing as there has not been much activity on this issue recently. If you have additional questions or concerns, please open a new issue.
