### ISSUE TITLE
Tests failing on CI

### ISSUE THREAD

**Issue by jkotalik** [aspnet/ServerTests#96]
Due to ANCM path changes I made.

**Comment by JunTaoLuo** [comment]
Are you referring to these failures http://aspnetci/viewLog.html?buildId=355009&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest? I think these tests are in IISIntegration.

**Comment by JunTaoLuo** [comment]
Nevermind that I think you are referring to http://aspnetci/viewLog.html?buildId=355021&tab=buildResultsDiv&buildTypeId=Lite_MusicStoreTest

**Comment by jkotalik** [comment]
#99

**Comment by jkotalik** [comment]
Tests are failing again. Should be fixed by https://github.com/aspnet/IISIntegration/commit/5d8670243c93bab486eeb5e995a2fbb4e6d1e203

**Comment by muratg** [comment]
@jkotalik what's the status of this? Still failing?

**Comment by jkotalik** [comment]
I need to discuss with @pan-wang regarding a 400 bad response issue we were seeing on CI. Tests are flaky and hang.

**Comment by pan-wang** [comment]
In case the application was not ready (i. e.,  the creation of app has not been detected by IIS),  the request is handled by site root and will lead to 400 error as the application cannot be found. We may need to add some delay to after updating applicationhost. config file.

**Comment by jkotalik** [comment]
Old issue that has been resolved.
